name: Embedded C CI/CD Pipeline

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu Klonla
        uses: actions/checkout@v4

      - name: Bağımlılıkları Yükle (GCC & Cppcheck)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cppcheck

      - name: 1. Statik Kod Analizi (Static Analysis)
        run: |
          cppcheck --enable=all --suppress=missingIncludeSystem --suppress=unusedFunction --suppress=staticFunction --error-exitcode=1 -I include src/

      - name: 2. Birim Testlerini Derle ve Çalıştır (Unit Tests)
        run: |
          make test

      - name: 3. Ana Uygulamayı Derle (Build App)
        run: |
          make
